---
- name: Reload networking (ifreload)
  ansible.builtin.command: ifreload -a
  when: proxmox_net_apply_reload | bool
  listen: "Reload networking (ifreload)"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  listen: "Update apt cache"

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  listen: "Update initramfs"

- name: Update grub
  ansible.builtin.command: update-grub
  listen: "Update grub"
