services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    user: "900:900"
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/jellyfin:/media:ro
    restart: unless-stopped
